# get vocab with types and frequences from two files generated by sent_lang_identification.py script with the sentences
# Author: Eirini Valkana
import collections


def get_types_freq_dict(input_file):
    vocab = set()
    tokens_total = []
    with open(input_file, "r") as infile:
        for line in infile:
            tokens = line.lower().split(" ")
            tokens_total += tokens
    vocab_dict = dict(collections.Counter(tokens_total))
    print(vocab_dict)
    return vocab_dict





# def main():
#     en_types_dict = {}
#     la_types_dict = {}
#     with open("./agree_sent_en.txt", "r") as en_file, open("./agree_sent_la.txt") as la_file:
#         for line


get_types_freq_dict("./agree_sent_en.txt")
